# Default values for pleroma.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: yournamehere/pleroma
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1"

pleromaImageOptions: # Settings dependent on how Docker image built
  mountPath: /pleroma/uploads # Where Docker image expects uploads to be mounted
  mixHome: /pleroma/.mix # The /path/to/.mix is usually found by WORKDIR in the Dockerfile
  port: 4000
  configPath: "/pleroma/config" # No trailing slash!
  configFile: prod.secret.exs


pleromaOptions:
  secret: "" # ADD ME!
  name: "Pleroma"
  email: "yourname@example.com"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: # Settings dependent on how Docker image built
  runAsUser: 911
  runAsGroup: 911
  fsGroup: 911

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: example.com
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

postgresql:
  postgresqlDatabase: pleroma
  postgresqlPassword: pleroma # CHANGE ME!!!
  postgresqlUsername: postgres # citext extension requires superuser to activate
  postgresqlPort: "5432"
  extensionImage: "docker.io/bitnami/postgresql:9.6" #Used for enabling extension

persistence:
  uploads:
    accessMode: ReadWriteOnce
    resources:
      requests:
        storage: 1Gi # How much storage for user uploads

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
