apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pleroma.fullname" . }}-env
  labels:
    {{- include "pleroma.labels" . | nindent 4 }}
data:
  DOMAIN: {{ .Values.pleromaOptions.domain }}
  INSTANCE_NAME: "Pleroma"
  POSTGRESQL_HOST: {{ template "pleroma.postgresql.fullname" . }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase }}
  POSTGRESQL_PORT: {{ .Values.postgresql.postgresqlPort | quote }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername }}
  DB_PASS: {{ .Values.postgresql.postgresqlPassword }}
