apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pleroma.fullname" . }}-env
  labels:
    {{- include "pleroma.labels" . | nindent 4 }}
data:
  DOMAIN: {{ .Values.pleromaOptions.domain }}
  INSTANCE_NAME: {{ .Values.pleromaOptions.name | quote }}
  ADMIN_EMAIL: {{ .Values.pleromaOptions.email | quote }}
  NOTIFY_EMAIL: {{ .Values.pleromaOptions.notifyEmail | quote }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase }}
  DB_HOST: {{ include "pleroma.fullname" . }}-postgresql
  SECRET_KEY_BASE: {{ .Values.pleromaOptions.secret | quote }}
