apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pleroma.fullname" . }}-env
  labels:
    {{- include "pleroma.labels" . | nindent 4 }}
data:
  POSTGRESQL_HOST: {{ template "pleroma.postgresql.fullname" . }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.postgresqlDatabase }}
  POSTGRESQL_PORT: {{ .Values.postgresql.postgresqlPort | quote }}
  POSTGRESQL_USERNAME: {{ .Values.postgresql.postgresqlUsername }}
