apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pleroma.fullname" . }}-enable-db-extension
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    metadata:
      name:  {{ include "pleroma.fullname" . }}-enable-db-extension
    spec:
      containers:
      - name: {{ include "pleroma.fullname" . }}-enable-db-extension
        image: {{ .Values.postgresql.extensionImage }}
        {{- if .Values.postgresql.enabled }}
        command: [ "bin/sh", "-c", 'psql -a -h {{ include "pleroma.postgresql.fullname" .}} -p  {{ .Values.postgresql.postgresqlPort }} -U {{ .Values.postgresql.postgresqlUsername }} -c "CREATE EXTENSION IF NOT EXISTS citext;"' ]
        {{- else }}
        command: [ "bin/sh", "-c", 'psql -a -h {{ .Values.externalPostgresql.host }} -p  {{ .Values.externalPostgresql.port }} -U {{ .Values.externalPostgresql.user }} -c "CREATE EXTENSION IF NOT EXISTS citext;"' ]
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ include "pleroma.fullname" . }}-env
        env:
          - name: "PGPASSWORD"
            valueFrom:
              secretKeyRef:
                {{- if .Values.postgresql.enabled }}
                name: {{ .Release.Name }}-postgresql
                key: postgresql-password
                {{- else }}
                name: {{ .Values.externalPostgresql.existingSecret }}
                key: {{ .Values.externalPostgresql.existingSecretPasswordKey }}
                {{- end }}
      restartPolicy: OnFailure
