apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pleroma.fullname" . }}-run-migration
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
spec:
  template:
    metadata:
      name:  {{ include "pleroma.fullname" . }}-run-migration
    spec:
      volumes:
        - name: config
          secret:
            secretName: {{ include "pleroma.fullname" . }}-configmap
      containers:
      - name: {{ include "pleroma.fullname" . }}-run-migration
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        args: [ "mix", "ecto.migrate" ]
        envFrom:
          - configMapRef:
              name: {{ include "pleroma.fullname" . }}-env
        env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "pleroma.fullname" . }}-postgresql
                key: postgresql-password
        volumeMounts:
          - name: config
            mountPath: {{ template "pleroma.configFullPath" . }}

      restartPolicy: OnFailure
