apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pleroma.fullname" . }}-configmap
  labels:
    {{- include "pleroma.labels" . | nindent 4 }}
stringData:
  {{ .Values.pleromaImageOptions.configFile }}: |
    import config

    config :pleroma, Pleroma.Web.Endpoint,
       secret_key_base: {{ .Values.pleromaOptions.secret | quote }}

    config :pleroma, :instance,
      registrations_open: false

    config :pleroma, configurable_from_database: true
