apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pleroma.fullname" . }}-uploads
  labels:
    {{- include "pleroma.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.uploads.accessMode }}
  resources:
    {{- toYaml .Values.persistence.uploads.resources | nindent 4}}
  storageClassName: {{ .Values.persistence.uploads.storageClassName }}
