apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pleroma.fullname" . }}-static
  labels:
    {{- include "pleroma.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.static.accessMode }}
  resources:
    {{- toYaml .Values.persistence.static.resources | nindent 4}}
  storageClassName: {{ .Values.persistence.static.storageClassName }}
